### ISSUE TITLE
Setup eslint

### ISSUE THREAD

**Issue by alienalien13** [illWatchers/ill-watch-ui#2]

**Comment by flashlee** [comment]
https://eslint.org/docs/rules/semi
So for now, if we decided to use `"semi": ["error", "never"]`, we need to keep in mind that default behavior of this rule is to ignore semicolons or lacking semicolon at the end of statements if the next line starts with `[`, `(`, `/`, `+`, or `-`
I'm strongly advocate to use object option `"beforeStatementContinuationChars": "always"`. For code aesthetics I would rather to use semi on a new line just before  `[`, `(`, `/`, `+`, or `-`. I'll search if there is any plugin with such rule and investigate a possibility to integrate it to our config

**Comment by flashlee** [comment]
Also probably we should consider including rule `no-unexpected-multiline`

**Comment by flashlee** [comment]
So from this https://github.com/standard/standard/blob/master/RULES.md#semicolons I understood that `no-unexpected-multiline` should be enough

**Comment by flashlee** [comment]
Also `no-unreachable: "error"` rule is nice to have also

**Comment by flashlee** [comment]
Btw I really liked [this "standart" plugin](https://github.com/standard/standard) so far. Maybe we can use it? @alienalien13 @maybelinot wdyt?

**Comment by maybelinot** [comment]
I can't get the point, why?
```
// ✓ ok
;`hello`.indexOf('o')

// ✗ avoid
`hello`.indexOf('o')
```

I do have lack of experience with production-like JS programming, so no objections from my side on any weird thing you'll come up with, just want to be sure that I understand why this is the standard..

**Comment by flashlee** [comment]
> I can't get the point, why?
> 
> ```
> // ✓ ok
> ;`hello`.indexOf('o')
> 
> // ✗ avoid
> `hello`.indexOf('o')
> ```
> I do have lack of experience with production-like JS programming, so no objections from my side on any weird thing you'll come up with, just want to be sure that I understand why this is the standard..

It's not a standart. The plugin I showed only called like this
The problem in ASI (automatic semicolon insertion). Expression like `'hello'.indexOf('o')` will cause a runtime error. So semicolon should be used here. But in order to save code aesthetics authors of "standart" plugin advice to put semi in front of such expressions (because every other line doesn't have it at the end)

**Comment by alienalien13** [comment]
@maybelinot 
```
const func = () => {}

func`lalalal` // this is calling a function "func"

func       // end this
`lalalal` // is the same as above
```
because of that you need some rule to avoid it.

**Comment by flashlee** [comment]
Also it's good to add rule [eol-last](https://eslint.org/docs/rules/eol-last). Airbnb preset doesn't have it.

**Comment by alienalien13** [comment]
@flashlee 
answering on this https://github.com/illWatchers/ill-watch-ui/pull/10#issuecomment-423743658

Use or not to use semicolons is a question mainly about personal preferences and habits, so there is no 100% right way. I confess that I've never thought about to not use semicolons, and I'm good with it. I've never had a problem with that. Even this second example, I've just tried it now, and it works somehow.
I am looking at [this](https://zellwk.com/blog/semicolons/) and following it next [article](https://feross.org/never-use-semicolons/), and I buy this:
 - `It is not going to make a big difference in the quality of your code.`
 - `There are actually many more “edge cases” to keep in mind with “always use semicolons” than with “never use semicolons”.`

And, yeah, TBH, it's my habit. However, it doesn't bring any issues or make code/projects fragile. And, as for me, code without semicolons in js a bit more readable.

So, I suggest to NOT to use semicolons. If anybody has an opposite habit - let's dig and discuss every pro and con. If not - let's move forward. 🤗

However, I like this approach to properly think about everything we do, it is the first and valuable symptom of a quality project. ❤️

**Comment by flashlee** [comment]
@alienalien13 I'm agree with both quotes. And despite of my habit to use semicolons, I'm ready to not use them, rules above should prevent from breaking code or unexpected behavior.
Only thing I'm not 100% sure of is side implementations of ASI in minifiers and transpilers. Just hope everything we are using in this project were created by people not so close minded as Douglas Crockford :sweat_smile:

**Comment by flashlee** [comment]
@alienalien13 @maybelinot 
So lets sum up what we will use:
* `"no-unexpected-multiline": "error"`
* `"no-unreachable": "error"`
* `"eol-last": ["error", "always"]`
It also good to have `"beforeStatementContinuationChars": "always"` but I don't really like that it requires `;` in the end of line before. I would prefer semicolon in the beginning of line. But if we are planing to create our own eslint plugin, we can [create our own rule](https://flexport.engineering/writing-custom-lint-rules-for-your-picky-developers-67732afa1803) for this (or modify `semi` rule)

**Comment by flashlee** [comment]
As soon as we agree on rules lets create another issue for adding these rules to our config

**Comment by alienalien13** [comment]
I'll create a package with this rules.

**Comment by alienalien13** [comment]
Just a note: of course it will not be a problem in case we will adjust it in dev progress. And it's a pretty good set for the begin 👍
